version: '3.7'

networks:
  alkemio_wallet_manager_net:

services:
  alkemio_wallet_manager:
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    container_name: alkemio_wallet_manager
    image: alkemio_wallet_manager
    build: .
    environment:
      - EMAIL_SMTP_HOST
      - RABBITMQ_HOST
      - LOGGING_CONSOLE_ENABLED
      - LOGGING_LEVEL_CONSOLE
    networks:
      - alkemio_wallet_manager_net
    restart: always
    command: npm run start
